title: "Brennan Drake Portfolio"
description: "Portfolio and Blog"
baseurl: "" # Leave empty if the site is at the root
url: "https://brennandrake.github.io/"
markdown: kramdown
theme: minima # Try this temporarily if you're not using a custom theme

permalink: none
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/

# Plugins (Optional)
plugins:
  - jekyll-feed
 # - jekyll-paginate 

future: true
paginate: 5